name: main_pytest
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8.1]
        
    steps:
      - uses: actions/checkout@v3      
      - run: make pytest
